export const userTypes = {
  CREATE_USER: "CREATE_USER",
  EDIT_USER: "EDIT_USER",
  LOGIN_USER: "LOGIN_USER",
  ADD_POST : "ADD_POST",
  LOGOUT: "LOGOUT",
  ADD_FAVORITE : "ADD_FAVORITE",
  DELETE_FAVORITE : "DELETE_FAVORITE",
  GET_FAVORITES : "GET_FAVORITES"
};

export const loadingTypes =  {
    TOGGLE_LOADING: 'TOGGLE_LOADING'
  }
  
