export const userTypes = {
  CREATE_USER: "CREATE_USER",
  EDIT_USER: "EDIT_USER",
  LOGIN_USER: "LOGIN_USER",
  ADD_POST : "ADD_POST",
  DELETE_POST : "DELETE_POST",
  LOGOUT: "LOGOUT",
  ADD_FAVORITE : "ADD_FAVORITE",
  DELETE_FAVORITE : "DELETE_FAVORITE",
  GET_FAVORITES : "GET_FAVORITES",
  LOGIN_WITH_EMAIL : "LOGIN_WITH_EMAIL",
  EDIT_POST : "EDIT_POST",
 
  
};

export const loadingTypes =  {
    TOGGLE_LOADING: 'TOGGLE_LOADING'
  }
  
